//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate
    {
        public int Id { get; set; }
        public int CurrencyId { get; set; }
        public decimal Value { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual Currency Currency { get; set; }
    }
}
